Maw Kit: Android/_IAPKit.cpp File Reference
_IAPKit.cpp File Reference
#include "../_IAPKit.hpp"
#include "../../Constants/IAPConstants.h"
#include "Constants.h"
#include <functional>
#include <vector>
#include "cocos2d.h"
#include "platform/android/jni/JniHelper.h"
#include <jni.h>
Functions
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback (JNIEnv *env, jobject thiz, jobjectArray stringArray)
Variables
std::map< MK::IAPKit::ProductID, std::vector< std::function< void(bool)> > > purchaseCallbacks
Function Documentation
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback (JNIEnv * env, jobject thiz, jobjectArray stringArray)
References MK::IAPKit::_buyButtonTitleForProduct(), MK::IAPKit::_buyIfPossible(), MK::IAPKit::_init(), MK::IAPKit::_restorePurchases(), MK::Android::APP_ACTIVITY, MK::IAPKit::productGlobalIDForProductLocalID(), MK::IAPKit::productLocalIDForProductGlobalID(), MK::IAPKit::productMetadataHasBeenRetrievedFromStore(), purchaseCallbacks, and MK::IAPKit::unlockProduct().
Variable Documentation
std::map<MK::IAPKit::ProductID, std::vector<std::function<void(bool)> > > purchaseCallbacks
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().