Maw Kit: Apple/Common/CPPUtils.mm File Reference
CPPUtils.mm File Reference
#include "CPPUtils.h"
#include <Foundation/Foundation.h>
#include <iostream>
Functions
NSData * HexToNSData (NSString *string)
Returns NSData with bytes represented by given hexadecimal NSString.
static char itoh (int i)
NSString * NSDataToHex (NSData *data)
Returns NSString with hexadecimal representation of given NSData.
NSArray< NSString * > * to_nsarray (const std::vector< std::string > &vec)
Returns a NSArray equivalent to given std::vector of strings.
NSDictionary< NSString *, NSString * > * to_nsdictionary (const std::map< std::string, std::string > &map)
Returns a NSDictionary equivalent to given std::map of strings.
NSDictionary< NSString *, NSNumber * > * to_nsdictionary (const std::map< std::string, double > &map)
Returns a NSDictionary equivalent to given std::map of key strings and double values.
NSDictionary< NSString *, NSNumber * > * to_nsdictionary (const std::map< std::string, long long > &map)
Returns a NSDictionary equivalent to given std::map of key strings and long long values.
NSDictionary< NSString *, NSNumber * > * to_nsdictionary (const std::map< std::string, bool > &map)
Returns a NSDictionary equivalent to given std::map of key strings and bool values.
NSString * to_nsstring (const std::string &string)
Returns a NSString equivalent to given std::string.
Function Documentation
NSData* HexToNSData (NSString * string)
Returns NSData with bytes represented by given hexadecimal NSString.
Parameters
string Hexadecimal string containing data.
Returns
Data represented by given hexadecimal string.
References MK::ABDatabase::init().
Referenced by ReceiptValidator::receiptAtURL:isValidForBundleID:andVersion:.
static char itoh (int i) inline static
Referenced by NSDataToHex().
NSString* NSDataToHex (NSData * data)
Returns NSString with hexadecimal representation of given NSData.
Parameters
data Data to be represented in hexadecimal.
Returns
Hexadecimal representation of given data.
References itoh().
Referenced by copy_mac_address().
NSArray<NSString *>* to_nsarray (const std::vector< std::string > & vec)
Returns a NSArray equivalent to given std::vector of strings.
Parameters
vec Vector to convert.
Returns
Equivalent NSArray.
References to_nsstring().
Referenced by RewardVideoDelegate::requestNewRewardVideo.
NSDictionary<NSString *, NSString *>* to_nsdictionary (const std::map< std::string, std::string > & map)
Returns a NSDictionary equivalent to given std::map of strings.
Parameters
map Map to convert.
Returns
Equivalent NSDictionary.
NSDictionary<NSString *, NSNumber *>* to_nsdictionary (const std::map< std::string, double > & map)
Returns a NSDictionary equivalent to given std::map of key strings and double values.
Parameters
map Map to convert.
Returns
Equivalent NSDictionary.
NSDictionary<NSString *, NSNumber *>* to_nsdictionary (const std::map< std::string, long long > & map)
Returns a NSDictionary equivalent to given std::map of key strings and long long values.
Parameters
map Map to convert.
Returns
Equivalent NSDictionary.
NSDictionary<NSString *, NSNumber *>* to_nsdictionary (const std::map< std::string, bool > & map)
Returns a NSDictionary equivalent to given std::map of key strings and bool values.
Parameters
map Map to convert.
Returns
Equivalent NSDictionary.
NSString* to_nsstring (const std::string & string)
Returns a NSString equivalent to given std::string.
Parameters
string String to convert.
Returns
Equivalent NSString.
Referenced by MK::KVDatabase::hasKey(), ReceiptValidator::receiptAtURL:isValidForBundleID:andVersion:, RewardVideoDelegate::requestNewRewardVideo, and to_nsarray().