Maw Kit: MK::Date Class Reference
MK::Date Class Reference
Date class is a wrapper for day-precision dates.
#include <Date.hpp>
Public Types
enum Month {
Month::January = 0, Month::February = 1, Month::March = 2, Month::April = 3,
Month::May = 4, Month::June = 5, Month::July = 6, Month::August = 7,
Month::September = 8, Month::October = 9, Month::November = 10, Month::December = 11
}
Enumeration holding months.
Public Member Functions
Date (std::time_t timestamp)
Returns a new date object given its UNIX timestamp.
Date (unsigned short day, Month month, unsigned long long year)
Returns a new date object for given day, month and year.
const unsigned short getDay () const
Returns day component of this date.
const Month getMonth () const
Returns month component of this date.
std::time_t getTimestamp () const
Returns UNIX timestamp for given date.
const unsigned long long getYear () const
Returns year component of this date.
bool operator< (const Date &rhs) const
Returns whether left hand side happened before right hand side.
bool operator== (const Date &rhs) const
Returns whether given dates are equal or not.
Static Public Member Functions
static const Date ChristmasEnd ()
Returns the last day of Christmas of this year.
static const Date ChristmasStart ()
Returns the first day of Christmas of this year.
static const Date EasterEnd ()
Returns the last day of Easter of this year.
static const Date EasterStart ()
Returns the first day of Easter of this year.
static const Date Today ()
Returns today's date.
Protected Attributes
std::time_t unixTimestamp
Timestamp of this date.
Detailed Description
Date class is a wrapper for day-precision dates.
Member Enumeration Documentation
enum MK::Date::Month strong
Enumeration holding months.
Enumerator
January
January.
February
February.
March
March.
April
April.
May
May.
June
June.
July
July.
August
August.
September
September.
October
October.
November
November.
December
December.
Constructor & Destructor Documentation
MK::Self::Date (std::time_t timestamp)
Returns a new date object given its UNIX timestamp.
Parameters
timestamp UNIX timestamp.
References unixTimestamp.
Referenced by ChristmasEnd(), ChristmasStart(), EasterEnd(), and EasterStart().
MK::Self::Date (unsigned short day, Month month, unsigned long long year)
Returns a new date object for given day, month and year.
Parameters
day Day.
month Month.
year Year.
References unixTimestamp.
Member Function Documentation
const Self MK::Self::ChristmasEnd () static
Returns the last day of Christmas of this year.
Returns
Last day of Christmas.
References Date(), December, getYear(), and Today().
const Self MK::Self::ChristmasStart () static
Returns the first day of Christmas of this year.
Returns
First day of Christmas.
References Date(), December, getYear(), and Today().
const Self MK::Self::EasterEnd () static
Returns the last day of Easter of this year.
Returns
Last day of Easter.
References Date(), and Today().
Referenced by EasterStart().
const Self MK::Self::EasterStart () static
Returns the first day of Easter of this year.
Returns
First day of Easter.
References Date(), and EasterEnd().
const unsigned short MK::Self::getDay () const
Returns day component of this date.
Returns
Day component of this date.
References unixTimestamp.
const Self::Month MK::Self::getMonth () const
Returns month component of this date.
Returns
Month component of this date.
References unixTimestamp.
std::time_t MK::Self::getTimestamp () const
Returns UNIX timestamp for given date.
Returns
UNIX timestamp for given date.
References unixTimestamp.
Referenced by operator<(), and operator==().
const unsigned long long MK::Self::getYear () const
Returns year component of this date.
Returns
Year component of this date.
References unixTimestamp.
Referenced by ChristmasEnd(), and ChristmasStart().
bool MK::Self::operator< (const Date & rhs) const inline
Returns whether left hand side happened before right hand side.
Parameters
rhs Right hand side.
Returns
true if left hand side happened before right hand side.
References getTimestamp().
bool MK::Self::operator== (const Date & rhs) const inline
Returns whether given dates are equal or not.
Parameters
rhs Right hand side.
Returns
true if both dates are equal.
References getTimestamp().
const Self MK::Self::Today () static
Returns today's date.
Returns
Date representing today.
Referenced by ChristmasEnd(), ChristmasStart(), and EasterEnd().
Member Data Documentation
std::time_t MK::Date::unixTimestamp protected
Timestamp of this date.
Referenced by Date(), getDay(), getMonth(), getTimestamp(), and getYear().
The documentation for this class was generated from the following files:
Date.hpp
Date.cpp