Maw Kit: MK::Range< T, typename > Class Template Reference
MK::Range< T, typename > Class Template Reference
A range defines a mathematical closed range starting at a value a and ending at a value b, both of them included in the range, mathematically expressed as \(\left [a,b\right ]\).
#include <Range.hpp>
Public Member Functions
const ValueType clamp (ValueType value) const
Returns given value clamped to this range.
const bool contains (ValueType value) const
Returns whether given value is contained in this range or not, mathematically speaking returns whether \(\mbox{start}\leq \mbox{value} \leq \mbox{end}\) holds or not.
const Range< double > doubleRange () const
Returns a new Range of double values starting and ending at the same values as this Range.
const ValueType first () const
Returns first value contained in this range.
const ValueType last () const
Returns last value contained in this range.
const size_t length () const
Returns the length of this range, that is, the amount of integer values such that \(\mbox{start}\leq \mbox{value}\leq \mbox{end}\) holds.
const Range< long long > longRange () const
Returns a new Range of long long values.
const bool operator< (MK::Range< T > rhs) const
Returns whether this range's first value is lower than given range's first value.
const bool operator== (MK::Range< T > rhs) const
Returns whether this range is equal to given range.
const bool operator> (MK::Range< T > rhs) const
Returns whether this range's last value is grater than given range's last value.
const bool operator[] (ValueType value) const
Returns whether given value is contained in this range or not, mathematically speaking returns whether \(\mbox{start}\leq \mbox{value} \leq \mbox{end}\) holds or not.
const ValueType randomFloatingPoint () const
Returns a random value contained in this range, that is, a random value such that \(\mbox{start}\leq \mbox{value}< \mbox{end}\) holds.
const ValueType randomInteger () const
Returns a random integer value contained in this range, that is, a random value such that \(\mbox{start}\leq \mbox{value}\leq \mbox{end}\) holds.
Range (const ValueType start, const ValueType end)
Creates a new range starting a start and ending at end, with both values included.
Range (const cocos2d::Vec2 &vector)
Creates a new range starting at x value and ending at y value of given cocos2d::Vec2.
Static Public Member Functions
static const Range RangeFromStartWithLength (const ValueType start, const size_t elements)
Returns a new range starting at start and containing elements integer elements, that is, ending at start + elements - 1.
static const Range RangeWithLengthUpToEnd (const size_t elements, const ValueType end)
Returns a new range ending containing elements integer elements and ending at end, that is, starting at end - elements + 1.
Protected Attributes
const ValueType firstElement
First element of this range.
const ValueType lastElement
Last element of this range.
Detailed Description
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type>
class MK::Range< T, typename >
A range defines a mathematical closed range starting at a value a and ending at a value b, both of them included in the range, mathematically expressed as \(\left [a,b\right ]\).
Any value \(a\leq x\leq b\) is considered to be included in the range.
Constructor & Destructor Documentation
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> MK::Range< T, typename >::Range (const ValueType start, const ValueType end) inline
Creates a new range starting a start and ending at end, with both values included.
Mathematically the new range is expressed as \(\left [\mbox{start},\mbox{end}\right ]\)
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> MK::Range< T, typename >::Range (const cocos2d::Vec2 & vector) inline
Creates a new range starting at x value and ending at y value of given cocos2d::Vec2.
Mathematically the new range is expressed as \(\left [\mbox{vector.x},\mbox{vector.y}\right ]\)
Member Function Documentation
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::clamp (ValueType value) const inline
Returns given value clamped to this range.
Parameters
value Value to be clamped.
Returns
Clamped value so it is contained in this range and the difference to original value is minimum.
References MK::Range< T, typename >::firstElement, and MK::Range< T, typename >::lastElement.
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const bool MK::Range< T, typename >::contains (ValueType value) const inline
Returns whether given value is contained in this range or not, mathematically speaking returns whether \(\mbox{start}\leq \mbox{value} \leq \mbox{end}\) holds or not.
Parameters
value Value to check if it is contained in this range or not.
Returns
true if given value is contained in this range or not.
References MK::Range< T, typename >::firstElement, and MK::Range< T, typename >::lastElement.
Referenced by MK::Range< T, typename >::operator[]().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const Range<double> MK::Range< T, typename >::doubleRange () const inline
Returns a new Range of double values starting and ending at the same values as this Range.
Useful to get floating point values from an integer Range.
Returns
New Range of double values starting and ending at the same values as this range.
References MK::Range< T, typename >::firstElement, and MK::Range< T, typename >::lastElement.
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::first () const inline
Returns first value contained in this range.
Returns
First value contained in this range.
References MK::Range< T, typename >::firstElement.
Referenced by MK::Range< T, typename >::operator<(), MK::Range< T, typename >::operator==(), and MK::Range< T, typename >::operator>().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::last () const inline
Returns last value contained in this range.
Returns
Last value contained in this range.
References MK::Range< T, typename >::lastElement.
Referenced by MK::Range< T, typename >::operator<(), MK::Range< T, typename >::operator==(), and MK::Range< T, typename >::operator>().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const size_t MK::Range< T, typename >::length () const inline
Returns the length of this range, that is, the amount of integer values such that \(\mbox{start}\leq \mbox{value}\leq \mbox{end}\) holds.
Returns
Amount of integer values contained in this range.
References MK::Range< T, typename >::firstElement, and MK::Range< T, typename >::lastElement.
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const Range<long long> MK::Range< T, typename >::longRange () const inline
Returns a new Range of long long values.
First value will be the result of rounding this range's first value as well as last value will be the one resulting of rounding this range's last value.
Returns
New Range of long long values starting and ending values near this range`s ones.
References MK::Range< T, typename >::firstElement, MK::Range< T, typename >::lastElement, and std::round().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const bool MK::Range< T, typename >::operator< (MK::Range< T > rhs) const inline
Returns whether this range's first value is lower than given range's first value.
Parameters
rhs Right hand side operand.
Returns
true if this range's first value is lower than given range's first value.
References MK::Range< T, typename >::first(), and MK::Range< T, typename >::last().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const bool MK::Range< T, typename >::operator== (MK::Range< T > rhs) const inline
Returns whether this range is equal to given range.
Parameters
rhs Right hand side operand.
Returns
true if both ranges start and end in the same values.
References MK::Range< T, typename >::first(), and MK::Range< T, typename >::last().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const bool MK::Range< T, typename >::operator> (MK::Range< T > rhs) const inline
Returns whether this range's last value is grater than given range's last value.
Parameters
rhs Right hand side operand.
Returns
true if this range's last value is greater than given range's last value.
References MK::Range< T, typename >::first(), and MK::Range< T, typename >::last().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const bool MK::Range< T, typename >::operator[] (ValueType value) const inline
Returns whether given value is contained in this range or not, mathematically speaking returns whether \(\mbox{start}\leq \mbox{value} \leq \mbox{end}\) holds or not.
Parameters
value Value to check if it is contained in this range or not.
Returns
true if given value is contained in this range or not.
References MK::Range< T, typename >::contains().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::randomFloatingPoint () const inline
Returns a random value contained in this range, that is, a random value such that \(\mbox{start}\leq \mbox{value}< \mbox{end}\) holds.
Returns
Random value contained in this range.
References MK::Range< T, typename >::firstElement, MK::Random::FloatingPointNumberInRange(), and MK::Range< T, typename >::lastElement.
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::randomInteger () const inline
Returns a random integer value contained in this range, that is, a random value such that \(\mbox{start}\leq \mbox{value}\leq \mbox{end}\) holds.
Returns
Random integer value contained in this range.
References MK::Range< T, typename >::firstElement, MK::Random::IntegerNumberInRange(), and MK::Range< T, typename >::lastElement.
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> static const Range MK::Range< T, typename >::RangeFromStartWithLength (const ValueType start, const size_t elements) inline static
Returns a new range starting at start and containing elements integer elements, that is, ending at start + elements - 1.
Mathematically the new range is expressed as \(\left [\mbox{start},\mbox{start}+\mbox{elements} - 1\right ]\).
Parameters
start First element contained in the range.
elements Amount of integer elements contained in new range.
Returns
New range \(\left [\mbox{start},\mbox{start}+ \mbox{elements}-1\right]\).
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> static const Range MK::Range< T, typename >::RangeWithLengthUpToEnd (const size_t elements, const ValueType end) inline static
Returns a new range ending containing elements integer elements and ending at end, that is, starting at end - elements + 1.
Mathematically the new range is expressed as \(\left [\mbox{end}-\mbox{elements}+1,\mbox{end}\right ]\).
Parameters
elements Last element contained in the range.
end Amount of integer elements contained in new range.
Returns
New range \(\left [\mbox{end}-\mbox{elements}+1,\mbox{end} \right]\).
Member Data Documentation
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::firstElement protected
First element of this range.
Referenced by MK::Range< T, typename >::clamp(), MK::Range< T, typename >::contains(), MK::Range< T, typename >::doubleRange(), MK::Range< T, typename >::first(), MK::Range< T, typename >::length(), MK::Range< T, typename >::longRange(), MK::Range< T, typename >::randomFloatingPoint(), and MK::Range< T, typename >::randomInteger().
template<typename T, typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type> const ValueType MK::Range< T, typename >::lastElement protected
Last element of this range.
Referenced by MK::Range< T, typename >::clamp(), MK::Range< T, typename >::contains(), MK::Range< T, typename >::doubleRange(), MK::Range< T, typename >::last(), MK::Range< T, typename >::length(), MK::Range< T, typename >::longRange(), MK::Range< T, typename >::randomFloatingPoint(), and MK::Range< T, typename >::randomInteger().
The documentation for this class was generated from the following file:
Range.hpp