Maw Kit: MK::Actions::MoveToNode Class Reference
MK::Actions::MoveToNode Class Reference
MoveToNode action moves a node from its original location to the location of given node, supporting moving to a node in movement.
#include <FiniteTimeActions.hpp>
Public Member Functions
virtual MoveToNode * clone () const override
bool initWithDuration (float duration, cocos2d::Node *destinationNode)
Initializes the action with given duration.
virtual MoveToNode * reverse (void) const override
virtual void startWithTarget (cocos2d::Node *target) override
virtual void update (float time) override
virtual ~MoveToNode ()
Static Public Member Functions
static MoveToNode * create (float duration, cocos2d::Node *destinationNode)
Creates an action that will move a node to the position of given node.
Public Attributes
CC_CONSTRUCTOR_ACCESS __pad0__: MoveToNode()
Protected Attributes
cocos2d::Node * destinationNode
Node to be reached at the end of the animation.
cocos2d::Point originalPosition
Original position of node to move.
Detailed Description
MoveToNode action moves a node from its original location to the location of given node, supporting moving to a node in movement.
Constructor & Destructor Documentation
MK::Actions::MoveToNode::~MoveToNode () virtual
Member Function Documentation
MoveToNode * MK::Actions::MoveToNode::clone () const override virtual
References initWithDuration().
MoveToNode * MK::Actions::MoveToNode::create (float duration, cocos2d::Node * destinationNode) static
Creates an action that will move a node to the position of given node.
Parameters
duration Duration of the animation.
destinationNode Destination node.
Returns
An autoreleased MoveToNode object.
References initWithDuration().
bool MK::Actions::MoveToNode::initWithDuration (float duration, cocos2d::Node * destinationNode)
Initializes the action with given duration.
Parameters
duration Duration of the animation.
destinationNode Destination node.
Returns
Whether this instance could be initialized properly or not.
Referenced by clone(), and create().
MoveToNode * MK::Actions::MoveToNode::reverse (void) const override virtual
void MK::Actions::MoveToNode::startWithTarget (cocos2d::Node * target) override virtual
void MK::Actions::MoveToNode::update (float time) override virtual
Member Data Documentation
CC_CONSTRUCTOR_ACCESS MK::Actions::MoveToNode::__pad0__
cocos2d::Node* MK::Actions::MoveToNode::destinationNode protected
Node to be reached at the end of the animation.
cocos2d::Point MK::Actions::MoveToNode::originalPosition protected
Original position of node to move.
The documentation for this class was generated from the following files:
FiniteTimeActions.hpp
FiniteTimeActions.cpp