Maw Kit: MK::Actions::RemoveFromParent Class Reference
MK::Actions::RemoveFromParent Class Reference
RemoveFromParent action removes a node from its parent after certain delay.
#include <FiniteTimeActions.hpp>
Public Member Functions
virtual RemoveFromParent * clone () const override
bool initWithDuration (float duration)
Initializes the action with given duration.
virtual RemoveFromParent * reverse (void) const override
virtual void startWithTarget (cocos2d::Node *target) override
virtual void update (float time) override
virtual ~RemoveFromParent ()
Static Public Member Functions
static RemoveFromParent * create (float duration)
Creates an action that will remove a node from its parent after certain delay.
Public Attributes
CC_CONSTRUCTOR_ACCESS __pad0__: RemoveFromParent()
Detailed Description
RemoveFromParent action removes a node from its parent after certain delay.
Constructor & Destructor Documentation
MK::Actions::RemoveFromParent::~RemoveFromParent () virtual
Member Function Documentation
RemoveFromParent * MK::Actions::RemoveFromParent::clone () const override virtual
References initWithDuration().
RemoveFromParent * MK::Actions::RemoveFromParent::create (float duration) static
Creates an action that will remove a node from its parent after certain delay.
Parameters
duration Seconds to wait before removing node from parent.
Returns
An autoreleased RemoveFromParent object.
References initWithDuration().
bool MK::Actions::RemoveFromParent::initWithDuration (float duration)
Initializes the action with given duration.
Parameters
duration Duration in seconds
Returns
Whether this instance could be initialized properly or not.
Referenced by clone(), and create().
RemoveFromParent * MK::Actions::RemoveFromParent::reverse (void) const override virtual
void MK::Actions::RemoveFromParent::startWithTarget (cocos2d::Node * target) override virtual
void MK::Actions::RemoveFromParent::update (float time) override virtual
Member Data Documentation
CC_CONSTRUCTOR_ACCESS MK::Actions::RemoveFromParent::__pad0__
The documentation for this class was generated from the following files:
FiniteTimeActions.hpp
FiniteTimeActions.cpp