Maw Kit: ReceiptValidator Class Reference
ReceiptValidator Class Reference
#import <ReceiptValidator.h>
Class Methods
(BOOL) + appReceiptIsValidForBundleID:andVersion:
(BOOL) + receiptAtURL:isValidForBundleID:andVersion:
(void) + validateAppReceiptForBundleID:andVersion:
Method Documentation
+ (BOOL) appReceiptIsValidForBundleID: (NSString *) bundleID andVersion: (NSString *) version
References MK::Device::isOSX(), and receiptAtURL:isValidForBundleID:andVersion:.
+ (BOOL) receiptAtURL: (NSURL *) receiptURL isValidForBundleID: (NSString *) bundleID andVersion: (NSString *) version
References HexToNSData(), MK::Device::isOSX(), to_nsstring(), and MK::Device::UUID().
Referenced by appReceiptIsValidForBundleID:andVersion:.
+ (void) validateAppReceiptForBundleID: (NSString *) bundleID andVersion: (NSString *) version
References MK::Device::isOSX().
The documentation for this class was generated from the following files:
Apple/Common/ReceiptValidator.h
Apple/Common/ReceiptValidator.mm