Maw Kit: StoreManager Class Reference
StoreManager Class Reference
Instance Methods
(void) - addCallback:
Adds given callback to the list of callbacks to be called when this manager is ready.
(void) - buyProductWithIdentifier:callingOnEnd:
Tries to buy product with given identifier, calling given callback on end.
(SKProduct *) - productWithIdentifier:
Returns product with given identifier.
(void) - restorePurchasesCallingOnEnd:
Tries to restore purchased items calling given callback on end.
Properties
voidManagerBoolLambda onBuyCallback
Callback to be called after a purchase.
NSMutableArray< voidManagerLambda > * pendingCallbacks
Callbacks to be called when request finishes.
NSMutableDictionary< NSString *, SKProduct * > * products
List of available products, indexed by ID.
BOOL purchasePending
Whether this store manager has a pending purchase or not.
BOOL ready
Whether this store manager is ready (remote request finished) or not.
SKProductsRequest * request
Request managed by this manager.
Method Documentation
- (void) addCallback: (voidManagerLambda) callback
Adds given callback to the list of callbacks to be called when this manager is ready.
If the manager is ready calls it immediately.
Parameters
callback Callback to call.
- (void) buyProductWithIdentifier: (MK::IAPKit::ProductID) identifier callingOnEnd: (voidManagerBoolLambda) callback
Tries to buy product with given identifier, calling given callback on end.
Parameters
identifier Global identifier of product to buy.
callback Callback to be called on end. Second parameter will be true if item was purchased.
References MK::Log::debug(), MK::Features::IAPKit, and productWithIdentifier:.
- (SKProduct *) productWithIdentifier: (MK::IAPKit::ProductID) identifier
Returns product with given identifier.
Parameters
identifier Identifier of product to return.
Returns
Product with given identifier.
Referenced by buyProductWithIdentifier:callingOnEnd:.
- (void) restorePurchasesCallingOnEnd: (voidManagerBoolLambda) callback
Tries to restore purchased items calling given callback on end.
Parameters
callback Callback to be called on end. Second parameter will be true if item was restored.
Property Documentation
- (voidManagerBoolLambda) onBuyCallback read write nonatomic copy
Callback to be called after a purchase.
- (NSMutableArray<voidManagerLambda>*) pendingCallbacks read write nonatomic strong
Callbacks to be called when request finishes.
- (NSMutableDictionary<NSString *, SKProduct *>*) products read write nonatomic strong
List of available products, indexed by ID.
Referenced by MK::IAPKit::productMetadataHasBeenRetrievedFromStore().
- (BOOL) purchasePending read write nonatomic assign
Whether this store manager has a pending purchase or not.
- (BOOL) ready read write nonatomic assign
Whether this store manager is ready (remote request finished) or not.
- (SKProductsRequest*) request read write nonatomic strong
Request managed by this manager.
Referenced by MK::IAPKit::_init().
The documentation for this class was generated from the following file:
Apple/Common/IAPKit.mm