Maw Kit: RewardVideoDelegate Class Reference
RewardVideoDelegate Class Reference
Instance Methods
(id) - initWithAdUnitID:andCallback:
(void) - requestNewRewardVideo
Properties
NSString * adUnitId
void(^ callback)(BOOL)
Method Documentation
- (id) initWithAdUnitID: (NSString *) adID andCallback: (void(^)(BOOL)) callback
References adUnitId, callback, and requestNewRewardVideo.
- (void) requestNewRewardVideo
References MK::AdKit::_init(), MK::AdKit::_showBottomBanner(), MK::AdKit::_showInterstitial(), MK::AdKit::_showTopBanner(), MK::AdKit::_showVideoReward(), MK::Features::AdKit, banners, delegates, MK::AdKit::enabled(), BannerViewDelegate::GADAdSizeForMKBannerSize:, interstitials, MK::Device::isUsingWifi(), MK::Analytics::logNonReadyVideoRewardDisplay(), MK::Log::nonCriticalCrash(), requestNewRewardVideo, GADMAdapterAdColonyInitializer::startWithAppID:andZones:andCustomID:, to_nsarray(), to_nsstring(), MK::AdKit::videoRewardsAvailable(), and MK::Log::warning().
Referenced by initWithAdUnitID:andCallback:, and requestNewRewardVideo.
Property Documentation
- (NSString*) adUnitId read write nonatomic strong
Referenced by initWithAdUnitID:andCallback:.
- (void(^ callback) (BOOL)) read write nonatomic copy
Referenced by initWithAdUnitID:andCallback:.
The documentation for this class was generated from the following file:
Apple/iOS/AdKit.mm