Maw Kit: MK::GameKit Namespace Reference
MK::GameKit Namespace Reference
GameKit namespace offers a secure wrapper for achievements and leaderboards backed by Game Center on Apple devices and Google Play Services on Android.
Enumerations
enum AchievementIndex : unsigned long long
Available achievements indexes.
enum LeaderboardIndex : unsigned long long
Available leaderboards indexes.
enum LoginState { LoginState::Pending = 0, LoginState::LoggedIn = 1, LoginState::NotLoggedIn = 2 }
LoginState represents possible states in a login process.
Functions
void _init ()
Inits native components of Game Kit.
void _reportAchievementProgress (const int achievementID, const float progress=1)
Reports given progress in achievement with given identifier, unlocking it if progress is \(\geq\).
void _requestAchievement (const int achievementID, std::function< void(float, bool)> callback=nullptr)
Requests player's current progress on given achievement and calls given callback.
void _requestFriendsScores (const int leaderboardID, std::function< void(std::map< std::string, unsigned long long >, bool)> callback=nullptr)
Requests current scores of current player's friends in given leaderboard and calls given callback once values are available.
void _requestScore (const int leaderboardID, VoidLongLongBoolCB callback=nullptr)
Requests current score from given leaderboard and calls given callback once value is available.
void _showLeaderboard (const int leaderbaordID)
Opens leaderboards UI for given leaderboard.
const bool _signInPlayer ()
Signs in player in Game Center.
void _submitScore (const long long score, const int leaderboardID)
Submits given score to given leaderboard.
void exitGame ()
Closes the game.
void init (std::function< void(void)> callback=nullptr)
Type of callbacks called after finishing an asynchronous request.
const bool isAvailable ()
On Android returns whether Google Play Games is available (true) or not.
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppAchievementCallback (JNIEnv *env, jobject thiz, jint id, jfloat progress, jboolean success)
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppFriendScoreCallback (JNIEnv *env, jobject thiz, jint id, jobjectArray names, jlongArray scores, jboolean success)
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppScoreCallback (JNIEnv *env, jobject thiz, jint id, jlong score, jboolean success)
void reportAchievementProgress (const AchievementIndex &achievementID, const float progress=1)
Reports achievement with given identifier and progress, unlocking it if progress is \(\geq\).
void requestAchievement (const AchievementIndex &achievementID, std::function< void(float, bool)> callback=nullptr)
Requests player's current progress on given achievement and calls given callback.
void requestFriendsScores (const LeaderboardIndex &leaderboardID, std::function< void(std::map< std::string, unsigned long long >, bool)> callback=nullptr)
Requests current scores of current player's friends in given leaderboard and calls given callback once values are available.
void requestScore (const LeaderboardIndex &leaderboardID, VoidLongLongBoolCB callback=nullptr)
Requests current score from given leaderboard and calls given callback once value is available.
void showAchievementsList ()
Shows achievements list screen.
void showLeaderboard (const LeaderboardIndex &leaderbaordID)
Opens leaderboards UI for given leaderboard.
void submitScore (const long long score, const LeaderboardIndex &leaderboardID)
Submits given score to given leaderboard.
Variables
std::map< int, std::vector< std::function< void(float, bool)> > > achievementCallbacks
NSArray< NSString * > * achievements
List of achievements.
LoginState currentLoginState = LoginState::Pending
Current login state.
std::map< int, std::vector< std::function< void(std::map< std::string, unsigned long long >, bool)> > > friendScoreCallbacks
NSArray< NSString * > * leaderboards
List of leaderboards.
std::map< int, std::vector< VoidLongLongBoolCB > > scoreCallbacks
Detailed Description
GameKit namespace offers a secure wrapper for achievements and leaderboards backed by Game Center on Apple devices and Google Play Services on Android.
Enumeration Type Documentation
enum MK::GameKit::AchievementIndex : unsigned long long strong
Available achievements indexes.
enum MK::GameKit::LeaderboardIndex : unsigned long long strong
Available leaderboards indexes.
enum MK::GameKit::LoginState strong
LoginState represents possible states in a login process.
Enumerator
Pending
User has not finished log in process yet.
LoggedIn
User has logged in.
NotLoggedIn
User has decided not to log in.
Function Documentation
void MK::GameKit::_init ()
Inits native components of Game Kit.
This method is implemented with platform-specific code
Referenced by init().
void MK::GameKit::_reportAchievementProgress (const int achievementID, const float progress = 1)
Reports given progress in achievement with given identifier, unlocking it if progress is \(\geq\).
This method is implemented with platform-specific code
Parameters
achievementID Achievement to unlock.
progress Progress of achievement to unlock, from 0 to 1.
References MK::Android::APP_ACTIVITY.
Referenced by reportAchievementProgress().
void MK::GameKit::_requestAchievement (const int achievementID, std::function< void(float, bool)> callback = nullptr)
Requests player's current progress on given achievement and calls given callback.
Callback's first parameter will be player's current progress on given achievement if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
This method is implemented with platform-specific code
Parameters
achievementID Achievement to be retrieved.
callback Callback to be called on success or failure.
References MK::Android::APP_ACTIVITY.
Referenced by requestAchievement().
void MK::GameKit::_requestFriendsScores (const int leaderboardID, std::function< void(std::map< std::string, unsigned long long >, bool)> callback = nullptr)
Requests current scores of current player's friends in given leaderboard and calls given callback once values are available.
Callback's first parameter will be a map of [player's name -> score] if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
This method is implemented with platform-specific code
Parameters
leaderboardID Leaderboard which current player's current score will be retrieved.
callback Callback to be called on success or failure.
References MK::Android::APP_ACTIVITY, and friendScoreCallbacks.
Referenced by requestFriendsScores().
void MK::GameKit::_requestScore (const int leaderboardID, VoidLongLongBoolCB callback = nullptr)
Requests current score from given leaderboard and calls given callback once value is available.
Callback's first parameter will be the score if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
This method is implemented with platform-specific code
Parameters
leaderboardID Leaderboard which current player's current score will be retrieved.
callback Callback to be called on success or failure.
References MK::Android::APP_ACTIVITY.
Referenced by requestScore().
void MK::GameKit::_showLeaderboard (const int leaderbaordID)
Opens leaderboards UI for given leaderboard.
This method is implemented with platform-specific code
Parameters
leaderbaordID Leaderboard to display.
References MK::Android::APP_ACTIVITY.
Referenced by showLeaderboard().
const bool MK::GameKit::_signInPlayer ()
Signs in player in Game Center.
This method is available on iOS but may not be available on other platforms
This method is available on OS X but may not be available on other platforms
This method is implemented with platform-specific code
References MK::Log::ErrorMessageFormat::METHOD_NOT_AVAILABLE_ON_ANDROID, and MK::Log::nonCriticalCrash().
void MK::GameKit::_submitScore (const long long score, const int leaderboardID)
Submits given score to given leaderboard.
This method is implemented with platform-specific code
Parameters
score Score to submit.
leaderboardID Leaderboard that will receive score.
References MK::Android::APP_ACTIVITY.
Referenced by submitScore().
void MK::GameKit::exitGame ()
Closes the game.
Note
Do NOT use cocos2d::Director::end() with MK::GameKit.
enum AchievementIndex unsigned long long typedef std::function< void(long long, bool)> VoidLongLongBoolCB void MK::GameKit::init (std::function< void(void)> callback = nullptr) strong
Type of callbacks called after finishing an asynchronous request.
Receives as first argument value retrieved and as second argument whether value was successfully retrieved (true) or not. Value unsuccessfully retrieved has no meaning and should not be used. Initializes internal data structures, local player and so on.
Parameters
callback Callback to be called after initialization.
References _init(), MK::Features::GameKitAchievements, and MK::Features::GameKitLeaderboards.
const bool MK::GameKit::isAvailable ()
On Android returns whether Google Play Games is available (true) or not.
On iOS and OS X returns whether Game Center is available and user has logged in (true) or not.
Returns
true if Google Play Games is available on Android or Game Center is available and user has logged in on iOS and OS X
References MK::Android::APP_ACTIVITY, and Java_org_cocos2dx_cpp_AppActivity_callCppScoreCallback().
Referenced by MK::AdKit::videoRewardsAvailable().
JNIEXPORT void JNICALL MK::GameKit::Java_org_cocos2dx_cpp_AppActivity_callCppAchievementCallback (JNIEnv * env, jobject thiz, jint id, jfloat progress, jboolean success)
References MK::Log::debug().
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppFriendScoreCallback().
JNIEXPORT void JNICALL MK::GameKit::Java_org_cocos2dx_cpp_AppActivity_callCppFriendScoreCallback (JNIEnv * env, jobject thiz, jint id, jobjectArray names, jlongArray scores, jboolean success)
References friendScoreCallbacks, and Java_org_cocos2dx_cpp_AppActivity_callCppAchievementCallback().
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppScoreCallback().
JNIEXPORT void JNICALL MK::GameKit::Java_org_cocos2dx_cpp_AppActivity_callCppScoreCallback (JNIEnv * env, jobject thiz, jint id, jlong score, jboolean success)
References MK::Log::debug(), and Java_org_cocos2dx_cpp_AppActivity_callCppFriendScoreCallback().
Referenced by isAvailable().
void MK::GameKit::reportAchievementProgress (const AchievementIndex & achievementID, const float progress = 1)
Reports achievement with given identifier and progress, unlocking it if progress is \(\geq\).
Parameters
achievementID Achievement to unlock.
progress Progress of achievement to unlock, from 0 to 1.
References _reportAchievementProgress(), and MK::Features::GameKitAchievements.
void MK::GameKit::requestAchievement (const AchievementIndex & achievementID, std::function< void(float, bool)> callback = nullptr)
Requests player's current progress on given achievement and calls given callback.
Callback's first parameter will be player's current progress on given achievement if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
Parameters
achievementID Achievement to be retrieved.
callback Callback to be called on success or failure.
References _requestAchievement(), and MK::Features::GameKitAchievements.
void MK::GameKit::requestFriendsScores (const LeaderboardIndex & leaderboardID, std::function< void(std::map< std::string, unsigned long long >, bool)> callback = nullptr)
Requests current scores of current player's friends in given leaderboard and calls given callback once values are available.
Callback's first parameter will be a map of [player's name -> score] if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
Parameters
leaderboardID Leaderboard which current player's current score will be retrieved.
callback Callback to be called on success or failure.
References _requestFriendsScores(), and MK::Features::GameKitLeaderboards.
void MK::GameKit::requestScore (const LeaderboardIndex & leaderboardID, VoidLongLongBoolCB callback = nullptr)
Requests current score from given leaderboard and calls given callback once value is available.
Callback's first parameter will be the score if the request succeeded and an invalid value if it didn't.
Callback's second parameter will be true if the request succeeded and false otherwise.
Parameters
leaderboardID Leaderboard which current player's current score will be retrieved.
callback Callback to be called on success or failure.
References _requestScore(), and MK::Features::GameKitLeaderboards.
void MK::GameKit::showAchievementsList ()
Shows achievements list screen.
This method is implemented with platform-specific code
References MK::Android::APP_ACTIVITY.
void MK::GameKit::showLeaderboard (const LeaderboardIndex & leaderbaordID)
Opens leaderboards UI for given leaderboard.
Parameters
leaderbaordID Leaderboard to display.
References _showLeaderboard(), and MK::Features::GameKitLeaderboards.
void MK::GameKit::submitScore (const long long score, const LeaderboardIndex & leaderboardID)
Submits given score to given leaderboard.
Parameters
score Score to submit.
leaderboardID Leaderboard that will receive score.
References _submitScore(), and MK::Features::GameKitLeaderboards.
Variable Documentation
std::map<int, std::vector<std::function<void(float, bool)> > > MK::GameKit::achievementCallbacks
NSArray< NSString * > * MK::GameKit::achievements
List of achievements.
LoginState MK::GameKit::currentLoginState = LoginState::Pending
Current login state.
std::map<int, std::vector<std::function<void(std::map<std::string, unsigned long long>, bool)> > > MK::GameKit::friendScoreCallbacks
Referenced by _requestFriendsScores(), and Java_org_cocos2dx_cpp_AppActivity_callCppFriendScoreCallback().
NSArray< NSString * > * MK::GameKit::leaderboards
List of leaderboards.
std::map<int, std::vector<VoidLongLongBoolCB> > MK::GameKit::scoreCallbacks