Maw Kit: MK::Analytics Namespace Reference
MK::Analytics Namespace Reference
Analytics namespace wraps Twitter's Fabric and MixPanel methods in a set of cross-compatible functions.
Namespaces
PerformanceIntensiveLogging
Fabric::PerformanceIntensiveLogging namespace features constants that allow enabling or disabling logging performance in an intensive way, as well as fine-tuning intensive performance logging intervals.
Functions
void _logEvent (const std::string &event)
Logs given event without additional attributes.
void _logEvent (const std::string &event, const std::map< std::string, std::string > &attr)
Logs given event with given additional attributes.
void _logEvent (const std::string &event, const std::map< std::string, double > &attr)
Logs given event with given additional attributes.
void _logLevelEnd (const std::string &levelName, const long long score, const bool succeeded, const std::map< std::string, std::string > &attr={})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
void _logLevelEnd (const std::string &levelName, const long long score, const bool succeeded, const std::map< std::string, double > &attr={})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
void _logLevelStart (const std::string &levelName, const std::map< std::string, std::string > &attr={})
Logs start of level with given name/identifier and given optional additional attributes.
void _logLevelStart (const std::string &levelName, const std::map< std::string, double > &attr={})
Logs start of level with given name/identifier and given optional additional attributes.
void _logPerformance (const bool isIntensive=false)
Logs frames per second.
const bool enabled ()
Returns whether Analytics logging in enbled or not.
void logEvent (const std::string &event)
Logs given event without additional attributes.
void logEvent (const std::string &event, const std::map< std::string, std::string > &attr)
Logs given event with given additional attributes.
void logEvent (const std::string &event, const std::map< std::string, double > &attr)
Logs given event with given additional attributes.
void logLevelEnd (const std::string &levelName, const long long score, const bool succeeded, const std::map< std::string, std::string > &attr={})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
void logLevelEnd (const std::string &levelName, const long long score, const bool succeeded, const std::map< std::string, double > &attr={})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
void logLevelStart (const std::string &levelName)
Logs start of level with given name/identifier.
void logLevelStart (const std::string &levelName, const std::map< std::string, std::string > &attributes)
Logs start of level with given name/identifier and given optional additional attributes.
void logLevelStart (const std::string &levelName, const std::map< std::string, double > &attributes)
Logs start of level with given name/identifier and given optional additional attributes.
void logNonReadyVideoRewardDisplay ()
Logs that app tried to display a video reward ad that was not ready yet.
void logPerformance (const bool isIntensive)
Logs frames per second.
Detailed Description
Analytics namespace wraps Twitter's Fabric and MixPanel methods in a set of cross-compatible functions.
Function Documentation
void MK::Analytics::_logEvent (const std::string & event)
Logs given event without additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
References MK::Android::APP_ACTIVITY.
Referenced by logEvent().
void MK::Analytics::_logEvent (const std::string & event, const std::map< std::string, std::string > & attr)
Logs given event with given additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
attr Additional attributes.
References MK::Android::APP_ACTIVITY.
void MK::Analytics::_logEvent (const std::string & event, const std::map< std::string, double > & attr)
Logs given event with given additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
attr Additional attributes.
References MK::Android::APP_ACTIVITY.
void MK::Analytics::_logLevelEnd (const std::string & levelName, const long long score, const bool succeeded, const std::map< std::string, std::string > & attr = {})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the finished level to log.
score Score use achieved in this level.
succeeded Whether used suceeded in this level (`true) or not.
attr Additional attributes to log in this event.
References MK::Android::APP_ACTIVITY.
Referenced by logLevelEnd().
void MK::Analytics::_logLevelEnd (const std::string & levelName, const long long score, const bool succeeded, const std::map< std::string, double > & attr = {})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the finished level to log.
score Score use achieved in this level.
succeeded Whether used suceeded in this level (`true) or not.
attr Additional attributes to log in this event.
References MK::Android::APP_ACTIVITY.
void MK::Analytics::_logLevelStart (const std::string & levelName, const std::map< std::string, std::string > & attr = {})
Logs start of level with given name/identifier and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the started level to log.
attr Additional attributes to log in this event.
References MK::Android::APP_ACTIVITY.
Referenced by logLevelStart().
void MK::Analytics::_logLevelStart (const std::string & levelName, const std::map< std::string, double > & attr = {})
Logs start of level with given name/identifier and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the started level to log.
attr Additional attributes to log in this event.
References MK::Android::APP_ACTIVITY.
void MK::Analytics::_logPerformance (const bool isIntensive = false)
Logs frames per second.
Parameters
isIntensive Whether this log is due to intensive performance information report or a regular performance information report. Defaults to false.
const bool MK::Analytics::enabled ()
Returns whether Analytics logging in enbled or not.
Returns
true if events should be logged in Fabric's Answers platform and MixPanel.
References MK::Features::Analytics.
Referenced by logEvent(), logLevelEnd(), and logLevelStart().
void MK::Analytics::logEvent (const std::string & event)
Logs given event without additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
References _logEvent(), and enabled().
Referenced by logNonReadyVideoRewardDisplay().
void MK::Analytics::logEvent (const std::string & event, const std::map< std::string, std::string > & attr)
Logs given event with given additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
attr Additional attributes.
References _logEvent(), and enabled().
void MK::Analytics::logEvent (const std::string & event, const std::map< std::string, double > & attr)
Logs given event with given additional attributes.
This method is implemented with platform-specific code
Parameters
event Name of the event to log.
attr Additional attributes.
References _logEvent(), and enabled().
void MK::Analytics::logLevelEnd (const std::string & levelName, const long long score, const bool succeeded, const std::map< std::string, std::string > & attr = {})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the finished level to log.
score Score use achieved in this level.
succeeded Whether used suceeded in this level (`true) or not.
attr Additional attributes to log in this event.
References _logLevelEnd(), and enabled().
void MK::Analytics::logLevelEnd (const std::string & levelName, const long long score, const bool succeeded, const std::map< std::string, double > & attr = {})
Logs end of level with given name/identifier, given score, whether user succeeded or not in the level and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the finished level to log.
score Score use achieved in this level.
succeeded Whether used suceeded in this level (`true) or not.
attr Additional attributes to log in this event.
References _logLevelEnd(), and enabled().
void MK::Analytics::logLevelStart (const std::string & levelName)
Logs start of level with given name/identifier.
Parameters
levelName Name of the started level to log.
void MK::Analytics::logLevelStart (const std::string & levelName, const std::map< std::string, std::string > & attributes)
Logs start of level with given name/identifier and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the started level to log.
attributes Additional attributes to log in this event.
References _logLevelStart(), and enabled().
void MK::Analytics::logLevelStart (const std::string & levelName, const std::map< std::string, double > & attributes)
Logs start of level with given name/identifier and given optional additional attributes.
This method is implemented with platform-specific code
Parameters
levelName Name of the started level to log.
attributes Additional attributes to log in this event.
References _logLevelStart(), and enabled().
void MK::Analytics::logNonReadyVideoRewardDisplay ()
Logs that app tried to display a video reward ad that was not ready yet.
References logEvent().
Referenced by RewardVideoDelegate::requestNewRewardVideo.
void MK::Analytics::logPerformance (const bool isIntensive)
Logs frames per second.
Parameters
isIntensive Whether this log is due to intensive performance information report or a regular performance information report. Defaults to false.