Maw Kit: MK::KVDatabase Namespace Reference
MK::KVDatabase Namespace Reference
KVDatabase namespace offers a key-value secure storage system stores content with a symmetric encryption in a way that users cannot decrypt data easily.
Namespaces
Default
Default values returned by KVDatabase.
Key
Well known KVDatabase keys.
Functions
const long long decreaseLongValueForKey (const std::string &key, const long long amount=1)
Decreases long value for given key by given amount.
void forcedWriteDisk ()
Forces writing KVDatabase changes to disk.
const long long getLongValueForKey (const std::string &key)
Returns long value associated with given key.
const std::string getStringValueForKey (const std::string &key)
Returns string value associated with given key.
const bool hasKey (NSString *key)
Return whether given key is in database or not.
const long long increaseLongValueForKey (const std::string &key, const long long amount=1)
Increases long value for given key by given amount.
void init (const std::function< void(void)> callback=nullptr)
Initializes key-value database and calls given callback if this is the first time database has been initialized since the game started.
const long long keepMaxLongValueForKey (const std::string &key, const long long proposedValue)
Keeps maximum long value between current long value and given value.
const long long keepMinLongValueForKey (const std::string &key, const long long proposedValue)
Keeps minimum long value between current long value and given value.
const long long setLongValueForKey (const std::string &key, const long long value)
Sets long value for given key.
const std::string setStringValueForKey (const std::string &key, const std::string &value)
Sets string value for given key.
const long long storeApplyingBinaryOperationAndReturningPreviousValue (const std::string &key, const long long value, const std::function< const long long(const long long, const long long)> &op)
Sets given key in database to the result of applying given binary operation to previous value (default value if no previous value available) and given value.
const std::vector< std::string > storedKeys ()
Variables
NSUserDefaults * db = [NSUserDefaults standardUserDefaults]
Detailed Description
KVDatabase namespace offers a key-value secure storage system stores content with a symmetric encryption in a way that users cannot decrypt data easily.
It is not meant to store privacy-critical information but data that you don't want users to easily see or modify.
Function Documentation
const long long MK::KVDatabase::decreaseLongValueForKey (const std::string & key, const long long amount = 1)
Decreases long value for given key by given amount.
Note
If there was no long value for given key this method is equivalent to setLongValueForKey.
Parameters
key Key to decrease.
amount Amount to decrease. Defaults to 1.
Returns
Previous long value for given key or MK::KVDatabase::Default::LONG.
References increaseLongValueForKey().
void MK::KVDatabase::forcedWriteDisk ()
Forces writing KVDatabase changes to disk.
This method is implemented with platform-specific code
Referenced by hasKey().
const long long MK::KVDatabase::getLongValueForKey (const std::string & key)
Returns long value associated with given key.
This method is implemented with platform-specific code
Parameters
key Key to retrieve.
Returns
Long value associated with given key or MK::KVDatabase::Default::LONG.
Referenced by MK::AdKit::enabled(), hasKey(), and storeApplyingBinaryOperationAndReturningPreviousValue().
const std::string MK::KVDatabase::getStringValueForKey (const std::string & key)
Returns string value associated with given key.
This method is implemented with platform-specific code
Parameters
key Key to retrieve.
Returns
String value associated with given key or MK::KVDatabase::Default::STRING.
Referenced by hasKey().
const bool MK::KVDatabase::hasKey (NSString * key)
Return whether given key is in database or not.
Parameters
key Key to check.
Returns
True if key is in database.
References forcedWriteDisk(), getLongValueForKey(), getStringValueForKey(), MK::KVDatabase::Default::LONG, SECRET_KEY, setLongValueForKey(), setStringValueForKey(), MK::KVDatabase::Default::STRING, and to_nsstring().
const long long MK::KVDatabase::increaseLongValueForKey (const std::string & key, const long long amount = 1)
Increases long value for given key by given amount.
Note
If there was no long value for given key this method is equivalent to setLongValueForKey.
Parameters
key Key to increase.
amount Amount to increase. Defaults to 1.
Returns
Previous long value for given key or MK::KVDatabase::Default::LONG.
References storeApplyingBinaryOperationAndReturningPreviousValue().
Referenced by decreaseLongValueForKey().
void MK::KVDatabase::init (const std::function< void(void)> callback = nullptr)
Initializes key-value database and calls given callback if this is the first time database has been initialized since the game started.
Parameters
callback Callback to be run after initialising database for the first time.
const long long MK::KVDatabase::keepMaxLongValueForKey (const std::string & key, const long long proposedValue)
Keeps maximum long value between current long value and given value.
Note
If there was no long value for given key MK::KVDatabase::Default::LONG is used as previous value.
Parameters
key Key to set.
proposedValue Proposed value.
Returns
Previous long value for given key or MK::KVDatabase::Default::LONG.
References storeApplyingBinaryOperationAndReturningPreviousValue().
const long long MK::KVDatabase::keepMinLongValueForKey (const std::string & key, const long long proposedValue)
Keeps minimum long value between current long value and given value.
Note
If there was no long value for given key MK::KVDatabase::Default::LONG is used as previous value.
Parameters
key Key to set.
proposedValue Proposed value.
Returns
Previous long value for given key or MK::KVDatabase::Default::LONG.
References storeApplyingBinaryOperationAndReturningPreviousValue().
const long long MK::KVDatabase::setLongValueForKey (const std::string & key, const long long value)
Sets long value for given key.
This method is implemented with platform-specific code
Parameters
key Key to set.
value Value to set.
Returns
Previous long value for given key or MK::KVDatabase::Default::LONG.
Referenced by hasKey(), and storeApplyingBinaryOperationAndReturningPreviousValue().
const std::string MK::KVDatabase::setStringValueForKey (const std::string & key, const std::string & value)
Sets string value for given key.
This method is implemented with platform-specific code
Parameters
key Key to set.
value Value to set.
Returns
Previous string value for given key or MK::KVDatabase::Default::STRING.
Referenced by hasKey().
const long long MK::KVDatabase::storeApplyingBinaryOperationAndReturningPreviousValue (const std::string & key, const long long value, const std::function< const long long(const long long, const long long)> & op)
Sets given key in database to the result of applying given binary operation to previous value (default value if no previous value available) and given value.
Will return previousy stored value for given key or given default value if there was not such a key.
Parameters
key Key to set.
value Value to pass to binary operator as second argument.
op Binary operation to perform to previous and new value.
Returns
Previous value in database for given key.
References getLongValueForKey(), and setLongValueForKey().
Referenced by increaseLongValueForKey(), keepMaxLongValueForKey(), and keepMinLongValueForKey().
const std::vector<std::string> MK::KVDatabase::storedKeys ()
Variable Documentation
NSUserDefaults* MK::KVDatabase::db = [NSUserDefaults standardUserDefaults]