Maw Kit: MK::IAPKit Namespace Reference
MK::IAPKit Namespace Reference
IAPKit namespace features methods to handle in-app purchases.
Enumerations
enum ProductID : unsigned long long
Available in app purchase indexes.
Functions
const std::string _buyButtonTitleForProduct (const ProductID productIdentifier)
Returns title of buy button for product with given identifier.
void _buyIfPossible (const ProductID productIdentifier, std::function< void(bool)> callback)
Tries to buy given item, calling callback on finished.
void _init (const std::vector< ProductID > &products, std::function< void(void)> callback=nullptr)
Inits In-App Purchase system, calling given callback on end.
void _restorePurchases (std::function< void(bool)> callback=nullptr)
Restores any previously purchased item, calling given callback on end.
const std::string buyButtonTitleForProduct (const ProductID productIdentifier)
Returns title of buy button for product with given identifier.
void buyIfPossible (const ProductID productIdentifier, std::function< void(bool)> callback)
Tries to buy given item, calling callback on finished.
const bool enabled ()
Returns whether IAPKit is enabled or not.
void init (const std::vector< ProductID > &products, std::function< void(void)> callback=nullptr)
Inits In-App Purchase system, calling given callback on end.
const std::string productGlobalIDForProductLocalID (const ProductID localID)
Returns string identifier (global ID) of given in-app purchase.
const ProductID productLocalIDForProductGlobalID (const std::string &globalID)
Returns enum class item (local ID) of in-app purchase with given string identifier (global ID).
const bool productMetadataHasBeenRetrievedFromStore (const ProductID productIdentifier)
Returns whether given product has been found on store and can be bought or not.
void restorePurchases (std::function< void(bool)> callback=nullptr)
Restores any previously purchased item, calling given callback on end.
void unlockProduct (const ProductID productIdentifier)
Detailed Description
IAPKit namespace features methods to handle in-app purchases.
Enumeration Type Documentation
enum MK::IAPKit::ProductID : unsigned long long strong
Available in app purchase indexes.
Function Documentation
const std::string MK::IAPKit::_buyButtonTitleForProduct (const ProductID productIdentifier)
Returns title of buy button for product with given identifier.
Title may include currency in user's expected format.
This method is implemented with platform-specific code
Parameters
productIdentifier Identifier of product whose buy button title will be returned.
Returns
Title to show in buy button for product with given identifier.
References storeManager.
Referenced by buyButtonTitleForProduct(), and Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
void MK::IAPKit::_buyIfPossible (const ProductID productIdentifier, std::function< void(bool)> callback)
Tries to buy given item, calling callback on finished.
This method is implemented with platform-specific code
Parameters
productIdentifier Identifier of product to buy.
callback Callback to be called. First argument will be true if user finished the purchase,
References MK::Log::debug().
Referenced by buyIfPossible(), and Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
void MK::IAPKit::_init (const std::vector< ProductID > & products, std::function< void(void)> callback = nullptr)
Inits In-App Purchase system, calling given callback on end.
This method is implemented with platform-specific code
Parameters
products List of products whose information will be downloaded.
callback Callback to be called.
References StoreManager::request, and storeManager.
Referenced by init(), and Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
void MK::IAPKit::_restorePurchases (std::function< void(bool)> callback = nullptr)
Restores any previously purchased item, calling given callback on end.
This method is implemented with platform-specific code
Parameters
callback Callback to be called after restoring purchases. First parameter will be true on success.
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback(), and restorePurchases().
const std::string MK::IAPKit::buyButtonTitleForProduct (const ProductID productIdentifier)
Returns title of buy button for product with given identifier.
Title may include currency in user's expected format.
Parameters
productIdentifier Identifier of product whose buy button title will be returned.
Returns
Title to show in buy button for product with given identifier.
References _buyButtonTitleForProduct(), and enabled().
void MK::IAPKit::buyIfPossible (const ProductID productIdentifier, std::function< void(bool)> callback)
Tries to buy given item, calling callback on finished.
Parameters
productIdentifier Identifier of product to buy.
callback Callback to be called. First argument will be true if user finished the purchase,
References _buyIfPossible(), and enabled().
const bool MK::IAPKit::enabled ()
Returns whether IAPKit is enabled or not.
Returns
true if IAPKit is enabled.
References MK::Features::IAPKit.
Referenced by buyButtonTitleForProduct(), buyIfPossible(), init(), and restorePurchases().
enum ProductID unsigned long long void MK::IAPKit::init (const std::vector< ProductID > & products, std::function< void(void)> callback = nullptr) strong
Inits In-App Purchase system, calling given callback on end.
Parameters
products List of products whose information will be downloaded.
callback Callback to be called.
References _init(), and enabled().
const std::string MK::IAPKit::productGlobalIDForProductLocalID (const ProductID localID)
Returns string identifier (global ID) of given in-app purchase.
Note
Your game should implement this method.
Parameters
localID LocalID (enum class item) of in-app purchase.
Returns
String identifier (global ID) of given in-app purchase.
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
const ProductID MK::IAPKit::productLocalIDForProductGlobalID (const std::string & globalID)
Returns enum class item (local ID) of in-app purchase with given string identifier (global ID).
Note
Your game should implement this method.
Parameters
globalID Global ID (string) of in-app purchase.
Returns
Enum class item (local ID) of given in-app purchase.
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
const bool MK::IAPKit::productMetadataHasBeenRetrievedFromStore (const ProductID productIdentifier)
Returns whether given product has been found on store and can be bought or not.
Note
This method does not check whether user already bought the product or not.
This method is implemented with platform-specific code
Parameters
productIdentifier Identifier of product to check.
Returns
true if product has been retrieved from store and can be bought.
References StoreManager::products, and storeManager.
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().
void MK::IAPKit::restorePurchases (std::function< void(bool)> callback = nullptr)
Restores any previously purchased item, calling given callback on end.
Parameters
callback Callback to be called after restoring purchases. First parameter will be true on success.
References _restorePurchases(), and enabled().
void MK::IAPKit::unlockProduct (const ProductID productIdentifier)
Referenced by Java_org_cocos2dx_cpp_AppActivity_callCppPurchasesCallback().