Maw Kit: MK::Random Namespace Reference
MK::Random Namespace Reference
Random namespace features utilities to get random numbers.
Functions
template<typename Iter , typename RandomGenerator >
Iter Choose (Iter start, Iter end, RandomGenerator &g)
Returns a random iterator between given start and end iterators, using given generator g to compute randomness.
template<typename Iter >
Iter Choose (Iter start, Iter end)
Returns a random iterator between given start and end iterators, using uniform probability.
template<class VectorValue >
VectorValue Choose (const std::vector< VectorValue > &vector)
Returns a random value in given vector.
template<typename Number , typename = typename std::enable_if<std::is_arithmetic<Number>::value, Number>::type>
const double FloatingPointNumberInRange (const Number min, const Number max)
Returns a floating point number in range \(\left[\mbox{min},\mbox{max} \right)\).
template<typename IntegerNumber , typename = typename std::enable_if<std::is_integral<IntegerNumber>::value, IntegerNumber>::type>
const IntegerNumber IntegerNumberInRange (const IntegerNumber min, const IntegerNumber max)
Returns an integer number in closed range \(\left[\mbox{min},\mbox{max} \right]\).
template<typename FPNumberBetweenZeroAndOne , typename = typename std::enable_if<std::is_arithmetic<FPNumberBetweenZeroAndOne>::value, FPNumberBetweenZeroAndOne>::type>
const bool TakeChance (const FPNumberBetweenZeroAndOne number)
Given a probability (floating point number between zero and one, both included) returns a random boolean value which will be true \(\mbox{number}\times100\%\) of times this method is called and false the other \(\left(1-\mbox{number}\right)\times100\%\).
Detailed Description
Random namespace features utilities to get random numbers.
Function Documentation
template<typename Iter , typename RandomGenerator > Iter MK::Random::Choose (Iter start, Iter end, RandomGenerator & g)
Returns a random iterator between given start and end iterators, using given generator g to compute randomness.
Parameters
start First iterator that can be selected.
end Last iterator, it cannot be selected.
g Generator of randomness.
Returns
Random iterator between given start and end iterators.
Referenced by Choose().
template<typename Iter > Iter MK::Random::Choose (Iter start, Iter end)
Returns a random iterator between given start and end iterators, using uniform probability.
Parameters
start First iterator that can be selected.
end Last iterator, it cannot be selected.
Returns
Random iterator between given start and end iterators.
References Choose().
template<class VectorValue > VectorValue MK::Random::Choose (const std::vector< VectorValue > & vector)
Returns a random value in given vector.
Parameters
vector Vector containing value to be returned.
Returns
Random value in given vector.
References Choose().
template<typename Number , typename = typename std::enable_if<std::is_arithmetic<Number>::value, Number>::type> const double MK::Random::FloatingPointNumberInRange (const Number min, const Number max)
Returns a floating point number in range \(\left[\mbox{min},\mbox{max} \right)\).
Parameters
min Minimum value (included) in the range.
max Maximum value (not included) in the range.
Returns
Floating point number in range \(\left[\mbox{min},\mbox{max} \right)\).
Referenced by MK::Range< T, typename >::randomFloatingPoint(), and TakeChance().
template<typename IntegerNumber , typename = typename std::enable_if<std::is_integral<IntegerNumber>::value, IntegerNumber>::type> const IntegerNumber MK::Random::IntegerNumberInRange (const IntegerNumber min, const IntegerNumber max)
Returns an integer number in closed range \(\left[\mbox{min},\mbox{max} \right]\).
Parameters
min Minimum value (included) in the range.
max Maximum value (included) in the range.
Returns
Integer number in closed range \(\left[\mbox{min},\mbox{max} \right]\).
Referenced by MK::Range< T, typename >::randomInteger().
template<typename FPNumberBetweenZeroAndOne , typename = typename std::enable_if<std::is_arithmetic<FPNumberBetweenZeroAndOne>::value, FPNumberBetweenZeroAndOne>::type> const bool MK::Random::TakeChance (const FPNumberBetweenZeroAndOne number)
Given a probability (floating point number between zero and one, both included) returns a random boolean value which will be true \(\mbox{number}\times100\%\) of times this method is called and false the other \(\left(1-\mbox{number}\right)\times100\%\).
Parameters
number Probability of returning true.
Returns
Randomly true or false taking into account given true probability.
References FloatingPointNumberInRange().