Maw Kit: MK::AdKit Namespace Reference
MK::AdKit Namespace Reference
AdKit namespace features methods to preload and display ads.
Enumerations
enum BannerSize {
BannerSize::StandardBanner = 0, BannerSize::LargeBanner = 1, BannerSize::IABMediumRectangle = 2, BannerSize::IABFullSizeBanner = 3,
BannerSize::IABLeaderboard = 4, BannerSize::SmartBannerPortrait = 5, BannerSize::SmartBannerLandscape = 6
}
Size of banner view ad.
Functions
void _init (std::string interstitialUnitID, std::string bottomBannerUnitID, BannerSize bottomBannerSize, std::string topBannerUnitID, BannerSize topBannerSize, std::string videoRewardUnitID, std::string adColonyAppID, std::string adColonyZoneID, std::string adColonyCustomID, std::vector< std::string > testingDevices)
Performs any initialization required by the ads adapter.
void _sessionEnd ()
void _sessionStart ()
void _showBottomBanner (std::string adUnitID)
Shows a bottom banner ad.
void _showInterstitial (std::string adUnitID)
Shows an interstitial ad.
void _showTopBanner (std::string adUnitID)
Shows a top banner ad.
void _showVideoReward (std::string adUnitID, std::function< void(bool)> callback)
Shows a video reward ad.
bool enabled ()
Returns whether ads are enabled for this user or not.
void init (std::string interstitialUnitID="", std::string bottomBannerUnitID="", BannerSize bottomBannerSize=BannerSize::SmartBannerPortrait, std::string topBannerUnitID="", BannerSize topBannerSize=BannerSize::SmartBannerPortrait, std::string videoRewardUnitID="", std::string adColonyAppID="", std::string adColonyZoneID="", std::string adColonyCustomID="", std::vector< std::string > testingDevices={})
Performs any initialization required by the ads adapter.
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_callCppRewardCallback (JNIEnv *env, jobject thiz, jboolean success)
void showBottomBanner (std::string adUnitID)
Shows a bottom banner ad.
void showInterstitial (std::string adUnitID)
Shows an interstitial ad.
void showTopBanner (std::string adUnitID)
Shows a top banner ad.
void showVideoReward (std::string adUnitID, std::function< void(bool)> callback)
Shows video reward ad.
bool videoRewardsAvailable ()
Returns whether this user has video rewards available or not.
Variables
std::vector< std::function< void(bool)> > rewardCallbacks
Detailed Description
AdKit namespace features methods to preload and display ads.
This methods automatically take into account whether Ads are enabled for this user or not.
Enumeration Type Documentation
enum MK::AdKit::BannerSize strong
Size of banner view ad.
Enumerator
StandardBanner
300x50, phones and tablets.
kGADAdSizeBanner.
LargeBanner
320x100, phones and tablets.
kGADAdSizeLargeBanner.
IABMediumRectangle
300x250, phones and tablets.
kGADAdSizeMediumRectangle.
IABFullSizeBanner
468x60, phones and tablets.
kGADAdSizeFullBanner.
IABLeaderboard
728x60, phones and tablets.
kGADAdSizeLeaderboard.
SmartBannerPortrait
screen width x 32|50|90, phones and tablets.
kGADAdSizeSmartBannerPortrait.
SmartBannerLandscape
screen width x 32|50|90, phones and tablets.
kGADAdSizeSmartBannerLandscape.
Function Documentation
void MK::AdKit::_init (std::string interstitialUnitID, std::string bottomBannerUnitID, BannerSize bottomBannerSize, std::string topBannerUnitID, BannerSize topBannerSize, std::string videoRewardUnitID, std::string adColonyAppID, std::string adColonyZoneID, std::string adColonyCustomID, std::vector< std::string > testingDevices)
Performs any initialization required by the ads adapter.
This method is implemented with platform-specific code
Note
Does not take into account whether ads are enabled or not,
Do not call this method directly.
Parameters
interstitialUnitID ID of interstitial Ad unit to be queried.
bottomBannerUnitID ID of bottom banner view Ad unit to be queried.
bottomBannerSize Size of bottom banner view Ad.
topBannerUnitID ID of top banner view Ad unit to be queried.
topBannerSize Size of top banner view Ad.
videoRewardUnitID ID of video reward Ad unit to be queried.
adColonyAppID ID of AdColony app to be queried.
adColonyZoneID ID of AdColony zone.
adColonyCustomID AdColony custom param.
testingDevices List of testing devices.
Referenced by init(), and RewardVideoDelegate::requestNewRewardVideo.
void MK::AdKit::_sessionEnd ()
void MK::AdKit::_sessionStart ()
void MK::AdKit::_showBottomBanner (std::string adUnitID)
Shows a bottom banner ad.
This method is implemented with platform-specific code
Note
Does not take into account whether ads are enabled or not,
Do not call this method directly.
Parameters
adUnitID ID of Ad unit to be queried.
Referenced by RewardVideoDelegate::requestNewRewardVideo, and showBottomBanner().
void MK::AdKit::_showInterstitial (std::string adUnitID)
Shows an interstitial ad.
This method is implemented with platform-specific code
Note
Does not take into account whether ads are enabled or not,
Do not call this method directly.
Parameters
adUnitID ID of Ad unit to be queried.
References MK::Android::APP_ACTIVITY.
Referenced by RewardVideoDelegate::requestNewRewardVideo, and showInterstitial().
void MK::AdKit::_showTopBanner (std::string adUnitID)
Shows a top banner ad.
This method is implemented with platform-specific code
Note
Does not take into account whether ads are enabled or not,
Do not call this method directly.
Parameters
adUnitID ID of Ad unit to be queried.
Referenced by RewardVideoDelegate::requestNewRewardVideo, and showTopBanner().
void MK::AdKit::_showVideoReward (std::string adUnitID, std::function< void(bool)> callback)
Shows a video reward ad.
This method is implemented with platform-specific code
Note
Does not take into account whether ads are enabled or not,
Do not call this method directly.
Parameters
adUnitID ID of Ad unit to be queried.
callback Callback to be called on video reward end. First parameter will be true if user should be rewarded.
References MK::Android::APP_ACTIVITY.
Referenced by RewardVideoDelegate::requestNewRewardVideo, and showVideoReward().
bool MK::AdKit::enabled ()
Returns whether ads are enabled for this user or not.
Returns
true if this user should see ads.
References MK::Features::AdKit, MK::KVDatabase::Key::ADS_DISABLED, MK::KVDatabase::getLongValueForKey(), MK::Device::isOSX(), and MK::KVDatabase::Default::LONG.
Referenced by init(), RewardVideoDelegate::requestNewRewardVideo, showBottomBanner(), showInterstitial(), showTopBanner(), and videoRewardsAvailable().
void MK::AdKit::init (std::string interstitialUnitID = "", std::string bottomBannerUnitID = "", BannerSize bottomBannerSize = BannerSize::SmartBannerPortrait, std::string topBannerUnitID = "", BannerSize topBannerSize = BannerSize::SmartBannerPortrait, std::string videoRewardUnitID = "", std::string adColonyAppID = "", std::string adColonyZoneID = "", std::string adColonyCustomID = "", std::vector< std::string > testingDevices = {})
Performs any initialization required by the ads adapter.
Parameters
interstitialUnitID ID of interstitial Ad unit to be queried.
bottomBannerUnitID ID of bottom banner view Ad unit to be queried.
bottomBannerSize Size of bottom banner view Ad.
topBannerUnitID ID of top banner view Ad unit to be queried.
topBannerSize Size of top banner view Ad.
videoRewardUnitID ID of video reward Ad unit to be queried.
adColonyAppID ID of AdColony app to be queried.
adColonyZoneID ID of AdColony zone.
adColonyCustomID AdColony custom param.
testingDevices List of testing devices.
References _init(), and enabled().
JNIEXPORT void JNICALL MK::AdKit::Java_org_cocos2dx_cpp_AppActivity_callCppRewardCallback (JNIEnv * env, jobject thiz, jboolean success)
Referenced by videoRewardsAvailable().
void MK::AdKit::showBottomBanner (std::string adUnitID)
Shows a bottom banner ad.
Parameters
adUnitID ID of Ad unit to be queried.
References _showBottomBanner(), and enabled().
void MK::AdKit::showInterstitial (std::string adUnitID)
Shows an interstitial ad.
References _showInterstitial(), and enabled().
void MK::AdKit::showTopBanner (std::string adUnitID)
Shows a top banner ad.
Parameters
adUnitID ID of Ad unit to be queried.
References _showTopBanner(), and enabled().
void MK::AdKit::showVideoReward (std::string adUnitID, std::function< void(bool)> callback)
Shows video reward ad.
Parameters
adUnitID ID of Ad unit to be queried.
callback Callback to be called on video reward end. First parameter will be true if user should be rewarded.
References _showVideoReward(), and videoRewardsAvailable().
bool MK::AdKit::videoRewardsAvailable ()
Returns whether this user has video rewards available or not.
This method is implemented with platform-specific code
Returns
Whether this user has video rewards available or not.
References MK::Android::APP_ACTIVITY, enabled(), MK::GameKit::isAvailable(), and Java_org_cocos2dx_cpp_AppActivity_callCppRewardCallback().
Referenced by RewardVideoDelegate::requestNewRewardVideo, and showVideoReward().
Variable Documentation
std::vector<std::function<void(bool)> > MK::AdKit::rewardCallbacks