Maw Kit: MK::Device Namespace Reference
MK::Device Namespace Reference
Device namespace features method to get information about this device's hardware.
Enumerations
enum Platform { Platform::Android = 0, Platform::iOS = 1, Platform::OSX = 2 }
Platform::Supported enum represents possible platforms where a MawKit game runs.
Functions
const Platform currentPlatform ()
Returns current platform.
const bool hasPowerfulHardware ()
Returns whether this device has powerful hardware or not.
const bool isAndroid ()
Returns whether this device is running Android or not.
const bool isInternetAvailable ()
Returns whether internet is currently available or not.
const bool isiOS ()
Returns whether this device is running iOS or not.
const bool isOSX ()
Returns whether this device is running OS X or not.
const bool isUsingCellularData ()
Returns whether internet is currently reachable via cellular data or not.
const bool isUsingWifi ()
Returns whether internet is currently reachable via Wifi or not.
const std::string language ()
Returns this device's language code.
const cocos2d::Size pxScreenSize ()
Retuns this device's screen size, in pixel.
const cocos2d::Size screenSize ()
Retuns this device's screen size, in points.
const std::string UUID ()
Returns UUID of this device.
Variables
constexpr float HD = 720 * 1280
Detailed Description
Device namespace features method to get information about this device's hardware.
Enumeration Type Documentation
enum MK::Device::Platform strong
Platform::Supported enum represents possible platforms where a MawKit game runs.
Enumerator
Android
iOS
OSX
Function Documentation
const Platform MK::Device::currentPlatform ()
Returns current platform.
Returns
Platform currently running this game.
References Android.
Referenced by copy_mac_address(), isAndroid(), isiOS(), and isOSX().
const bool MK::Device::hasPowerfulHardware ()
Returns whether this device has powerful hardware or not.
Returns
true if this device's hardware can run Hop Raider at 60 fps.
References HD.
Referenced by copy_mac_address().
const bool MK::Device::isAndroid ()
Returns whether this device is running Android or not.
Returns
true is this device is running Android.
References Android, and currentPlatform().
const bool MK::Device::isInternetAvailable ()
Returns whether internet is currently available or not.
Returns
true if internet is currently reachable.
const bool MK::Device::isiOS ()
Returns whether this device is running iOS or not.
Returns
true is this device is running iOS.
References currentPlatform(), and iOS.
const bool MK::Device::isOSX ()
Returns whether this device is running OS X or not.
Returns
true is this device is running OS X.
References currentPlatform(), and OSX.
Referenced by ReceiptValidator::appReceiptIsValidForBundleID:andVersion:, MK::AdKit::enabled(), ReceiptValidator::receiptAtURL:isValidForBundleID:andVersion:, and ReceiptValidator::validateAppReceiptForBundleID:andVersion:.
const bool MK::Device::isUsingCellularData ()
Returns whether internet is currently reachable via cellular data or not.
Returns
true if this device is connected to the internet through cellular data.
const bool MK::Device::isUsingWifi ()
Returns whether internet is currently reachable via Wifi or not.
Returns
true if this device is connected to the internet through Wifi.
Referenced by RewardVideoDelegate::requestNewRewardVideo.
const std::string MK::Device::language ()
Returns this device's language code.
Returns
This device's language code.
const cocos2d::Size MK::Device::pxScreenSize ()
Retuns this device's screen size, in pixel.
This method is implemented with platform-specific code
Returns
Size of this device's screen in pixels.
References screenSize().
Referenced by copy_mac_address().
const cocos2d::Size MK::Device::screenSize ()
Retuns this device's screen size, in points.
This method is implemented with platform-specific code
Returns
Size of this device's screen in points.
Referenced by copy_mac_address(), and pxScreenSize().
const std::string MK::Device::UUID ()
Returns UUID of this device.
Note
Current implementation of this method returns a fixed string.
This method is implemented with platform-specific code
Returns
UUID of this device.
Referenced by copy_mac_address(), ReceiptValidator::receiptAtURL:isValidForBundleID:andVersion:, and MK::CryptoKit::symmetricEncrypt().
Variable Documentation
constexpr float MK::Device::HD = 720 * 1280
Referenced by hasPowerfulHardware().