Maw Kit: MK::GameKit::ReplayKit Namespace Reference
MK::GameKit::ReplayKit Namespace Reference
GameKit::ReplayKit wraps GameCenter's ReplayKit framework introduced in iOS 9.
Functions
void discardRecording (std::function< void(void)> callback=nullptr)
Discards current recording.
bool hasRecordedReplay ()
Returns whether this is a replay recorded or not.
const bool isAvailable ()
Returns whether ReplayKit is available.
void showLastRecordedReplayEditor ()
Shows last recording editor and share options, if any.
void startRecording (bool microphoneEnabled=false, std::function< void(bool)> callback=nullptr)
Starts recording.
void stopRecording (std::function< void(bool)> callback=nullptr)
Stops recording.
Detailed Description
GameKit::ReplayKit wraps GameCenter's ReplayKit framework introduced in iOS 9.
This method is available on iOS but may not be available on other platforms
Function Documentation
void MK::GameKit::ReplayKit::discardRecording (std::function< void(void)> callback = nullptr)
Discards current recording.
Note
Also discards any recorded replay.
This method is available on iOS but may not be available on other platforms
Parameters
callback Callback to be called when recording is discarted.
References MK::Log::debug(), isAvailable(), RPPVCDelegate::lastRecordingPreviewVC, and stopRecording().
bool MK::GameKit::ReplayKit::hasRecordedReplay ()
Returns whether this is a replay recorded or not.
This method is available on iOS but may not be available on other platforms
Returns
true if there is a replay recorded.
References RPPVCDelegate::lastRecordingPreviewVC.
Referenced by showLastRecordedReplayEditor().
const bool MK::GameKit::ReplayKit::isAvailable ()
Returns whether ReplayKit is available.
ReplayKit is available in iPhone 5S and newer and on iPad Air / iPad mini 2 and newer.
This method is available on iOS but may not be available on other platforms
Returns
true if ReplayKit is available on this device.
Referenced by discardRecording(), startRecording(), and stopRecording().
void MK::GameKit::ReplayKit::showLastRecordedReplayEditor ()
Shows last recording editor and share options, if any.
This method is available on iOS but may not be available on other platforms
References hasRecordedReplay().
void MK::GameKit::ReplayKit::startRecording (bool microphoneEnabled = false, std::function< void(bool)> callback = nullptr)
Starts recording.
This method is available on iOS but may not be available on other platforms
Parameters
microphoneEnabled Whether microphone should be enabled or not.
callback Callback to be called when system starts recording. Callback's parameter will be false if there was an error.
References MK::Log::debug(), and isAvailable().
void MK::GameKit::ReplayKit::stopRecording (std::function< void(bool)> callback = nullptr)
Stops recording.
This method is available on iOS but may not be available on other platforms
Parameters
callback Callback to be called when recording is stopped. First parameter will be true on success.
References MK::Log::debug(), and isAvailable().
Referenced by discardRecording().