Maw Kit: MK::Log Namespace Reference
MK::Log Namespace Reference
Log namespace offers methods to easily log warning, error, debug-only and information messages.
Namespaces
ErrorMessageFormat
Log::ErrorMessageFormat namespace wraps constants defining well-known errors.
Functions
void critical (const char *format,...)
Logs a critical message that will appear also in release builds and will also be logged to Fabric.
void debug (const char *format,...)
Logs a debug message that will not appear also in release builds.
void nonCriticalCrash (const char *format,...)
Logs a non critical message that will appear also in release builds and will also be logged to Fabric.
void toFabric (const char *format, va_list list)
Logs message with given format and additional data to Fabric's Crashlytics service.
void warning (const char *format,...)
Logs a warning message that will appear also in release builds.
Detailed Description
Log namespace offers methods to easily log warning, error, debug-only and information messages.
Each method will log message to a different subset of output files:
warning: debug, release
debug: debug
critical: debug, release, Fabric (as critical)
nonCriticalCrash: debug, release, Fabric (as non-critical)
Function Documentation
void MK::Log::critical (const char * format, ...)
Logs a critical message that will appear also in release builds and will also be logged to Fabric.
Parameters
format Format.
... Additional parameters.
void MK::Log::debug (const char * format, ...)
Logs a debug message that will not appear also in release builds.
Parameters
format Format.
... Additional parameters.
Referenced by MK::IAPKit::_buyIfPossible(), StoreManager::buyProductWithIdentifier:callingOnEnd:, MK::GameKit::Java_org_cocos2dx_cpp_AppActivity_callCppAchievementCallback(), and MK::GameKit::Java_org_cocos2dx_cpp_AppActivity_callCppScoreCallback().
void MK::Log::nonCriticalCrash (const char * format, ...)
Logs a non critical message that will appear also in release builds and will also be logged to Fabric.
Parameters
format Format.
... Additional parameters.
References toFabric().
Referenced by MK::GameKit::_signInPlayer(), and RewardVideoDelegate::requestNewRewardVideo.
void MK::Log::toFabric (const char * format, va_list list)
Logs message with given format and additional data to Fabric's Crashlytics service.
Parameters
format Message to be logged's format.
list Additional data.
Referenced by nonCriticalCrash().
void MK::Log::warning (const char * format, ...)
Logs a warning message that will appear also in release builds.
Parameters
format Format.
... Additional parameters.
Referenced by copy_mac_address(), and RewardVideoDelegate::requestNewRewardVideo.